language: python
matrix:
  fast_finish: true
  include:
    - python: "3.6"
      env: TOXENV=coverall
    - python: "3.6"
      env: TOXENV=flake8
    - python: "3.6"
      env: TOXENV=pydoc
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py37
      dist: xenial
      sudo: true
install: pip install -U setuptools tox coveralls
script: tox
after_success: coveralls